# This is a Jekyll configuration file.
# For more information, see: https://jekyllrb.com/docs/configuration/
# For a list of available options, see: https://jekyllrb.com/docs/configuration/options/
# For a list of available plugins, see: https://jekyllrb.com/docs/plugins/
# For a list of available themes, see: https://jekyllrb.com/docs/themes/
# For a list of available layouts, see: https://jekyllrb.com/docs/layouts/
# For a list of available includes, see: https://jekyllrb.com/docs/includes/
# For a list of available posts, see: https://jekyllrb.com/docs/posts/
# For a list of available pages, see: https://jekyllrb.com/docs/pages/
# For a list of available collections, see: https://jekyllrb.com/docs/collections/
# For a list of available data files, see: https://jekyllrb.com/docs/datafiles/
# For a list of available assets, see: https://jekyllrb.com/docs/assets/
# For a list of available plugins, see: https://jekyllrb.com/docs/plugins/
title: My Profile
webpage: https://www.linkedin.com/in/jworozco/
description: >-
  Welcome to my personal website! I'm Jose W Orozco, an Electronics Engineer with a passion for Music. 
  Here, you'll find insights into my work, projects, and hobbies. Let's connect and create something amazing together!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jworozco

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
